+incdir+rtl/include
+define+FPGA
+define+HAS_UART
rtl/include/config.svh
rtl/include/board_defs.svh
rtl/pkg/soc_types_pkg.sv
rtl/common/edge_detect.sv
rtl/common/reset_sync.sv
rtl/core/cpu_stub.sv
rtl/bus/bus_mux.sv
rtl/ip/uart_core.sv
rtl/ip/timer_core.sv
rtl/ip/generic_ram.sv
rtl/ip/ram_wrapper.sv
rtl/feature_switch.sv
rtl/soc_top.sv
