+incdir+rtl/include
+incdir+tb
+define+SIMULATION
+define+USE_VENDOR_RAM_MODEL
rtl/include/config.svh
rtl/include/board_defs.svh
rtl/pkg/soc_types_pkg.sv
rtl/common/edge_detect.sv
rtl/common/reset_sync.sv
rtl/core/cpu_stub.sv
rtl/bus/bus_mux.sv
rtl/ip/uart_core.sv
rtl/ip/timer_core.sv
rtl/ip/generic_ram.sv
tb/models/vendor_ram_model.sv
rtl/ip/ram_wrapper.sv
rtl/feature_switch.sv
rtl/soc_top.sv
tb/tb_soc.sv
